### ISSUE TITLE
Add function for change identity

### ISSUE THREAD

**Issue by mtbitcr** [BitcoinCredit/E-Bills#71]
We need the ability to change our data. In the future this will be done with mint nodes. But at the moment, for MVP we need to be able to do it from our profile.

TODO:
- [x]  A function on the backend side that changes the identity and also enters the changes into the DHT.
- [x]  Endpoint
- [x]  Function in frontend to change an identity. It should be done in the same way as when creating an identity. That is, we first need to enter the data, then see all the changes, and then send it to the frontend. Also, we need to make qualitative input (no empty values, no change of age and so on).

**Comment by upoi** [comment]
It took me a while to figure out but this all can be achieved very simply. I just added an "Edit" Button that puts the page back in to the sign = true state and enables changing of the fields. From there the same Preview and Sign Buttons are used. So by that we also can use the /identity/create call which will use the backend function to write the identy to the file and send it to dht. 
@mtbitcr If you see problems with this aproach let me know

**Comment by upoi** [comment]
@mtbitcr did you mean that birth date should not be changeg or just that it also has to be checked for validity of date?

**Comment by mtbitcr** [comment]
> @mtbitcr did you mean that birth date should not be changeg or just that it also has to be checked for validity of date?
Both logical things (like a person can't change their date of birth) and more technically-legal things (age can't be under 18 or over 120) must be respected

**Comment by mtbitcr** [comment]
> It took me a while to figure out but this all can be achieved very simply. I just added an "Edit" Button that puts the page back in to the sign = true state and enables changing of the fields. From there the same Preview and Sign Buttons are used. So by that we also can use the /identity/create call which will use the backend function to write the identy to the file and send it to dht. @mtbitcr If you see problems with this aproach let me know

@upoi In principle, the idea is not bad. But it needs to be adapted a bit. In the future we plan to introduce an Identity Chain that will reflect everything that happens with Identity. There will be blocks, with different "Operation Codes". One of the codes will be Identity changes. And that's where we'll put only Identity changes. In your approach, you're just kind of "re-creating" an existing identity. That's bad.
It's also a very bad programming practice to rewrite all the data.
A good approach has 3 steps:
- get an identity object from the frontend (where only the fields we changed will be populated);
- get the Identity object from our local storage (note that it may return an empty value or nothing);
- on the basis of these 2 objects form our new identity, then write it locally and in DHT.
This way it will be easy to create blocks with changed fields in the future.
